INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,false,'Wydanie "Dziadów" kompletne bez skrótów i cięć w treści. W tym wydaniu znajdziesz odpowiedzi na pytania z podręcznika - "pewniak na teście", czyli wskazanie zagadnień, które zwykle pojawiają się w pytaniach z danej lektury we wszelkich testach sprawdzających wiedzę, a także w podręcznikach i na klasówkach. Zawiera bardzo szczegółowe streszczenie oraz drugie skrócone, ułatwiające szybkie przygotowanie się przed lekcją. Opracowanie zawiera plan wydarzeń, wnikliwie wyjaśnioną problematykę oraz szerokie charakterystyki bohaterów.','https://ecsmedia.pl/c/dziady-w-iext39528243.jpg',1832,'Dziady');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Historia szlachecka z okresu poprzedzającego wyprawę Napoleona na Moskwę. W utworze tym można wskazać elementy eposu, pokazuje on bowiem bohaterskie czyny wielkich postaci na tle przełomowych dla narodu wydarzeń. Stał się on epopeją narodową, gdyż wyrażał najważniejsze treści w chwili, gdy narodowi było to niezbędne oraz krzepił serca.','https://www.greg.pl/imgs/covers/380/Pan-Tadeusz_lkpt.jpg',1834,'Pan Tadeusz');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'"Konrad Wallenrod", powieść historyczna z dziejów litewskich i pruskich jest powieścią poetycką, jednym ze sztandarowych gatunków romantyzmu. Mickiewicz napisał ją w 1828 roku na zesłaniu w Petersburgu. Choć akcja rozgrywa się w średniowiecznym Malborku i na Litwie, w istocie utwór porusza problematykę narodowowyzwoleńczą.Tytułowym bohaterem jest Litwin Walter Alf, który w dzieciństwie został porwany przez Krzyżaków i wychowany w zakonie na pruskiego rycerza. Przygotowywany przez starego wajdelotę do pomszczenia Litwy, przeszedł wewnętrzą przemianę przybrał imię Konrad Wallenrod i przygotował zemstę na swoich zakonnych współbraciach. Do jej realizacji doszło, gdy został mistrzem zakonu. Wyprowadził krzyżackich rycerzy na wojną z Litwą, gdzie wpędził ich w pułapkę. Postawa Konrada Wallenroda zawiera się w pojęciu wallenrodyzmu, nadającemu nowe znaczenie moralne postępowi i zdradzie, ponieważ mają na celu walkę o wolność uciemiężonego narodu','https://cf1-taniaksiazka.statiki.pl/images/popups/6A3/9788377916025.jpg',1828,'Konrad Wallenrod');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Lektura wraz opracowaniem to znakomita pomoc i inspiracja dla uczniów oraz nauczycieli. Tekst opatrzono wskazówkami interpretacyjnymi i hasłami ułatwiającymi nawigację po książce – dzięki nim łatwo znaleźć potrzebny w trakcie omawiania lektury fragment, zgromadzić materiały do wypracowań i ustnych wypowiedzi, zapamiętać najważniejsze informacje i utrwalić znajomość lektury. Zamieszczone na końcu książki opracowanie podporządkowano podstawie programowej. Zawiera ono ciekawy biogram autora, streszczenie, mapę mentalną, najważniejsze zagadnienia omawiane na lekcjach, a także wiele inspirujących informacji, podpowiedzi i zadań, dzięki którym czytanie lektury staje się twórczą przygodą.Opracowanie powstało pod kierunkiem Katarzyny Zioły-Zemczak, nauczycielki języka polskiego z bogatym doświadczeniem w pracy z dziećmi i młodzieżą, wieloletniej doradczyni metodycznej, a obecnie konsultantki ds. języka polskiego pracującej na co dzień z nauczycielami.','https://www.nieprzeczytane.pl/images/photos/okladki/136/135046/__b_9788375171860.jpg',1822,'Ballady i romanse');
INSERT INTO AUTHORS(author_id,name,surname) VALUES(null,'Adam','Mickiewicz');
INSERT INTO AUTHOR_BOOK(author_id,book_id) VALUES(1,1);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(1,2);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(1,3);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(1,4);

INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Od ponad stu lat historia niezwykłej miłości młodego patrycjusza rzymskiego i pięknej zakładniczki chrześcijanki wzrusza i fascynuje kolejne pokolenia czytelników. Trzymająca w napięciu akcja oraz wspaniały w swej wyrazistości i barwności obraz Rzymu za czasów Nerona.Wydanie z opracowaniem.','https://ecsmedia.pl/c/quo-vadis-b-iext39255599.jpg',1896,'Quo vadis');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Rok 1655, w granice Rzeczpospolitej wkracza olbrzymia armia szwedzka. Polacy zapamiętają ten najazd jako "potop szwedzki”. Mnożą się zdrady - ulega szlachta pospolitego ruszenia pod Ujściem, Janusz Radziwiłł poddaje Litwę Szwedom. Ostoją Polaków staje się Częstochowa, w której obronie niebagatelną rolę odegra Andrzej Kmicic. Bohaterskimi czynami za wszelką cenę będzie chciał odzyskać dobre imię polskiego szlachcica.','https://ecsmedia.pl/c/potop-w-iext38864542.jpg',1886,'Potop');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Ogniem i mieczem jest pierwszą powieścią historyczną z cyklu zwanego Trylogią, w skład którego wchodzą także Potop i Pan Wołodyjowski. Akcja powieści rozgrywa się w latach 1648–1651 w czasie powstania Chmielnickiego na Ukrainie. Dramatyczne wydarzenia historyczne z dziejów Rzeczypospolitej przeplatają się z losami bohaterów powołanych do życia przez Henryka Sienkiewicza: Jana Skrzetuskiego, Heleny Kurcewiczówny, Jana Onufrego Zagłoby, Longinusa Podbipięty czy Jurko Bohuna. Dzięki geniuszowi autora, postacie stały się w oczach czytelników autentyczne, a ich pasjonujące losy znalazły ważne miejsce w świadomości narodowej Polaków. Ogniem i mieczem, wydane w 1884 roku, odegrało ogromną rolę w kształtowaniu się postaw patriotycznych w końcowym okresie zaborów, a co za tym idzie w odrodzeniu się niepodległej Polski.','https://fwcdn.pl/fpo/01/37/137/6900290.3.jpg',1884,'Ogniem i mieczem');
INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'W tym wydaniu znajdziesz odpowiedzi na pytania z podręcznika - "pewniak na teście", czyli wskazanie zagadnień, które zwykle pojawiają się w pytaniach z danej lektury we wszelkich testach sprawdzających wiedzę, a także w podręcznikach i na klasówkach. Zawiera bardzo szczegółowe streszczenie oraz drugie skrócone, ułatwiające szybkie przygotowanie się przed lekcją. Opracowanie zawiera plan wydarzeń, wnikliwie wyjaśnioną problematykę oraz szerokie charakterystyki bohaterów.W tynieckiej gospodzie "Pod Lutym Turem" dwaj rycerze z Bogdańca, Maćko i jego synowiec, młodziutki Zbyszko, spotykają się z dworem księżnej Anny Danuty. Zbyszko od pierwszego wejrzenia zakochuje się w jednej z dwórek księżnej, Danusi. Nie spodziewa się, jak bardzo dziewczyna zostanie skrzywdzona przez Krzyżaków, jeszcze nie wie, że w wielkiej wojnie z Zakonem, która wkrótce się rozegra on, Zbyszko, weźmie udział również z osobistych powodów.','https://cdn-lubimyczytac.pl/upload/books/4920000/4920604/800588-352x500.jpg',1900,'Krzyżacy');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Henryk','Sienkiewicz');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(2,5);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(2,6);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(2,7);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(2,8);


INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'William nie jest mężczyzną w typie Olimpii. Wydaje się, że ich znajomość skończy się po jednym spacerze ulicami Torunia, ale William ma wobec dziewczyny inne plany i nie spocznie, dopóki nie osiągnie celu. To opowieść o Kopciuszku, w której nie ma złej macochy, ale jest okrutny ojciec. Jest bajkowa miłość, ale są i całkiem zwyczajne problemy. Jest mnóstwo śmiałych scen, które wywołują wypieki na twarzy, ale i tak najważniejsza jest miłość, która jest w stanie pokonać wszystkie przeciwności losu.','https://cdn-lubimyczytac.pl/upload/books/4955000/4955248/874600-352x500.jpg',2021,'Nieosiągalny');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Małgorzata','Falkowska');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Ewelina','Nawara');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(3,9);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(4,9);

INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Pewnej nocy Mina podsłuchała rozmowę dwóch niebezpiecznych, mówiących po rosyjsku mężczyzn, którzy siedzieli w barze, gdzie pracowała jako kelnerka. Chociaż udawała, że nie zna tego języka i nic nie zrozumiała, oni z jakiegoś powodu wiedzieli, że tak nie było.Gdy Mina kończy pracę, czuje, że coś jest nie tak. Szybko się dowiaduje, dlaczego miała takie wrażenie. Zanim się zorientuje, zostaje porwana prosto z ulicy.Mężczyźni zapewniają ją, że nic jej nie grozi. Ma tylko zostać z nimi do rana. Sprawa się jednak komplikuje, ponieważ jeden z nich wzbudza w Minie pożądanie. Kobieta ma świadomość, że to nie powinno mieć miejsca i nie jest normalne. Ale ona nie jest zwyczajną dziewczyną, o czym dwóch rosyjskich zabójców nie wie.Żaden z nich nie ma pojęcia, że Mina jest tak samo groźna jak oni.','https://cdn-lubimyczytac.pl/upload/books/4956000/4956182/876321-352x500.jpg',2021,'Rosyjski zabójca');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Chairmaine','Pauls');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Anna','Zaires');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(5,10);
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(6,10);


INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Babia Góra to popularny szczyt, który każdego roku przyciąga tysiące turystów. Czy halny wiatr może wywiewać echa tajemnic, które zdarzyły się na stokach góry? Baśka Zajda jest bohaterką "W cieniu Babiej Góry". Wraca z Krakowa w rodzinne strony zmęczona życiem i codziennymi obowiązkami. Zdolna policjantka, która być może została wyrzucona z policji wojewódzkiej, chociaż ona sama nie chce o tym rozmawiać. W urokliwej Zawoi ma zamiar zapomnieć o codzienności i w końcu odpocząć. Jej najlepsza przyjaciółka Iza niedługo bierze ślub, dlatego wraz w towarzystwie koleżanek wybierają się na Babią Górę - wieczór panieński w górach może być ciekawą formą spędzenia wolnego czasu z dala od mężczyzn.','https://cf1-taniaksiazka.statiki.pl/images/large/B78/9788366718241.jpg',2021,'W cieniu Babiej Góry');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Irena','Małysa');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(7,11);


INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Wkrótce Jamie będzie musiał zmierzyć się z własnymi demonami. Nowojorska policja liczy na jego pomoc. Mistrz grozy przedstawia nietypowy kryminał z elementami sensacji oraz horroru.Jamie Conklin marzy o normalnym życiu. Tego samego pragnie również samotnie wychowująca go matka. Oboje dobrze wiedzą, że nie ma na to żadnych szans.Chłopiec urodził się z nietypową umiejętnością, dzięki której jest w stanie dostrzegać zmarłych. Daje mu to niesamowitą okazję na poznanie ich tajemnic, odkrycie tego, co znajduje się poza percepcją przeciętnych ludzi. Ma to jednak swoją cenę, dlatego za namową matki Jamie ukrywa ten fakt przed innymi. Wszystko się zmienia, kiedy jego sekret poznaje detektyw nowojorskiej policji - oczekuje pomocy chłopca w śledztwie. Młody bohater będzie musiał zapomnieć o dziecięcej niewinności, by wziąć udział w walce dobra ze złem.','https://cf1-taniaksiazka.statiki.pl/images/large/C61/9788382153613.jpg',2021,'Później');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Stephen','King');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(8,12);


INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Lata czterdzieste XX wieku. Czechosłowację okupują Niemcy. Izabela jest niezwykle charakterną dziewczyną z Vražnégo. Pewnego dnia całe jej życie zmienia się diametralnie. A wszystko dlatego, że Izabela poznaje kaprala Billa Kinga, brytyjskiego jeńca wojennego. Para z miejsca zakochuje się w sobie bez pamięci, jednak rodzice dziewczyny nie mogą o niczym się dowiedzieć.Mimo to jednak Izabela i Bill biorą naprędce zorganizowany, potajemny ślub. Postanawiają uciec z okupowanego kraju. Obmyślają sprytny plan, ale plan ten spełza na niczym. Niemcy aresztują śmiałków, a przebrana w żołnierski mundur Izabela zostaje wzięta omyłkowo za mężczyznę. Postanawia nie wyprowadzać nazistów z błędu. Chce być blisko ukochanego. Razem trafiają do niemieckiego obozu koncentracyjnego w Lamsdorf. Izabela musi nadal ukrywać swoją płeć. Każdego dnia ryzykuje dosłownie wszystko.','https://cf1-taniaksiazka.statiki.pl/images/popups/716/9788366718937.jpg',2021,'Żona więźnia');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Maggie','Brookes');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(9,13);

INSERT INTO BOOKS(book_id,available,description,image,published,title) VALUES(null,true,'Barack ObamaJeśli chcesz się dowiedzieć, co kierowało byłym prezydentem podczas podejmowania decyzji, które miały zaważyć na losach całego amerykańskiego społeczeństwa, koniecznie sięgnij po "Ziemię obiecaną".Droga Baracka Obamy nigdy nie była idealna. Na każdym kroku, szczególnie po objęciu prezydentury, pojawiały się okoliczności, które przynosiły ze sobą mnóstwo wahań i rozczarowań. Autor najnowszej książki podkreśla, że one również były ważne, by kraj rósł w siłę i stale się rozwijał.','https://cf1-taniaksiazka.statiki.pl/images/large/21A/9788326845833.jpg',2021,'Ziemia obiecana');
INSERT INTO AUTHORS(author_id,name,surname)  VALUES(null,'Barack','Obama');
INSERT INTO AUTHOR_BOOK(author_id,book_id)  VALUES(10,14);
